// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (username, time_zone) VALUES ($1, $2)
RETURNING id, username, time_zone, created_at, deletion_requested_at
`

type CreateAccountParams struct {
	Username string
	TimeZone string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Username, arg.TimeZone)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.TimeZone,
		&i.CreatedAt,
		&i.DeletionRequestedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, username, time_zone, created_at, deletion_requested_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.TimeZone,
		&i.CreatedAt,
		&i.DeletionRequestedAt,
	)
	return i, err
}

const updateAccountProfile = `-- name: UpdateAccountProfile :one
UPDATE accounts SET username = $2, time_zone = $3
WHERE id = $1 AND deletion_requested_at IS NULL
RETURNING id, username, time_zone, created_at, deletion_requested_at
`

type UpdateAccountProfileParams struct {
	ID       pgtype.UUID
	Username string
	TimeZone string
}

func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountProfile, arg.ID, arg.Username, arg.TimeZone)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.TimeZone,
		&i.CreatedAt,
		&i.DeletionRequestedAt,
	)
	return i, err
}
