// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts DEFAULT VALUES
RETURNING id, time_zone, created_at
`

func (q *Queries) CreateAccount(ctx context.Context) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount)
	var i Account
	err := row.Scan(&i.ID, &i.TimeZone, &i.CreatedAt)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, time_zone, created_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(&i.ID, &i.TimeZone, &i.CreatedAt)
	return i, err
}
