// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_limits.sql

package db

import (
	"context"
)

const countAuthRequests = `-- name: CountAuthRequests :one
INSERT INTO auth_rate_limits (key) VALUES ($1)
ON CONFLICT (key) DO UPDATE SET
    request_count = CASE WHEN auth_rate_limits.window_start <= now() - interval '1 hour'
                         THEN 1 ELSE auth_rate_limits.request_count + 1 END,
    window_start = CASE WHEN auth_rate_limits.window_start <= now() - interval '1 hour'
                        THEN now() ELSE auth_rate_limits.window_start END
RETURNING request_count
`

func (q *Queries) CountAuthRequests(ctx context.Context, key []byte) (int32, error) {
	row := q.db.QueryRow(ctx, countAuthRequests, key)
	var request_count int32
	err := row.Scan(&request_count)
	return request_count, err
}

const pruneAuthLimits = `-- name: PruneAuthLimits :exec
DELETE FROM auth_rate_limits WHERE window_start < now() - interval '2 hours'
`

func (q *Queries) PruneAuthLimits(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneAuthLimits)
	return err
}
