// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_login.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeEmailChallenge = `-- name: CompleteEmailChallenge :exec
UPDATE email_login_challenges
SET verified_at = now(), completion_token_hash = $2, completed_at = now()
WHERE id = $1
`

type CompleteEmailChallengeParams struct {
	ID                  pgtype.UUID
	CompletionTokenHash []byte
}

func (q *Queries) CompleteEmailChallenge(ctx context.Context, arg CompleteEmailChallengeParams) error {
	_, err := q.db.Exec(ctx, completeEmailChallenge, arg.ID, arg.CompletionTokenHash)
	return err
}

const consumeRecoveryTicket = `-- name: ConsumeRecoveryTicket :execrows
UPDATE email_login_challenges SET completion_token_hash = $2
WHERE completion_token_hash = $1 AND completed_at > now() - interval '10 minutes'
`

type ConsumeRecoveryTicketParams struct {
	CompletionTokenHash   []byte
	CompletionTokenHash_2 []byte
}

func (q *Queries) ConsumeRecoveryTicket(ctx context.Context, arg ConsumeRecoveryTicketParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRecoveryTicket, arg.CompletionTokenHash, arg.CompletionTokenHash_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEmailChallenge = `-- name: CreateEmailChallenge :one
INSERT INTO email_login_challenges (id, email, purpose, code_mac, expires_at)
VALUES ($1, $2, 'sign_in', $3, now() + interval '10 minutes')
RETURNING id
`

type CreateEmailChallengeParams struct {
	ID      pgtype.UUID
	Email   string
	CodeMac []byte
}

func (q *Queries) CreateEmailChallenge(ctx context.Context, arg CreateEmailChallengeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createEmailChallenge, arg.ID, arg.Email, arg.CodeMac)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteEmailChallenge = `-- name: DeleteEmailChallenge :exec
DELETE FROM email_login_challenges WHERE id = $1 AND completed_at IS NULL
`

func (q *Queries) DeleteEmailChallenge(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailChallenge, id)
	return err
}

const failEmailAttempt = `-- name: FailEmailAttempt :exec
UPDATE email_login_challenges SET attempt_count = attempt_count + 1 WHERE id = $1
`

func (q *Queries) FailEmailAttempt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, failEmailAttempt, id)
	return err
}

const lockEmailChallenge = `-- name: LockEmailChallenge :one
SELECT id, email, code_mac, attempt_count, expires_at, verified_at, completed_at
FROM email_login_challenges WHERE id = $1 AND purpose = 'sign_in' FOR UPDATE
`

type LockEmailChallengeRow struct {
	ID           pgtype.UUID
	Email        string
	CodeMac      []byte
	AttemptCount int16
	ExpiresAt    pgtype.Timestamptz
	VerifiedAt   pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
}

func (q *Queries) LockEmailChallenge(ctx context.Context, id pgtype.UUID) (LockEmailChallengeRow, error) {
	row := q.db.QueryRow(ctx, lockEmailChallenge, id)
	var i LockEmailChallengeRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeMac,
		&i.AttemptCount,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CompletedAt,
	)
	return i, err
}

const lockRecoveryTicket = `-- name: LockRecoveryTicket :one
SELECT id, email FROM email_login_challenges
WHERE completion_token_hash = $1 AND purpose = 'sign_in'
  AND completed_at > now() - interval '10 minutes' FOR UPDATE
`

type LockRecoveryTicketRow struct {
	ID    pgtype.UUID
	Email string
}

func (q *Queries) LockRecoveryTicket(ctx context.Context, completionTokenHash []byte) (LockRecoveryTicketRow, error) {
	row := q.db.QueryRow(ctx, lockRecoveryTicket, completionTokenHash)
	var i LockRecoveryTicketRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const restoreEmailAccount = `-- name: RestoreEmailAccount :one
UPDATE accounts AS a SET deletion_requested_at = NULL
FROM login_identities AS i
WHERE i.subject = $1 AND i.provider = 'email' AND i.account_id = a.id
  AND a.deletion_requested_at IS NOT NULL
  AND a.deletion_requested_at > now() - interval '30 days'
RETURNING a.id
`

func (q *Queries) RestoreEmailAccount(ctx context.Context, subject string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, restoreEmailAccount, subject)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
