// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoginIdentity = `-- name: CreateLoginIdentity :one
INSERT INTO login_identities (account_id, provider, subject)
VALUES ($1, $2, $3)
RETURNING id, account_id, provider, subject, linked_at
`

type CreateLoginIdentityParams struct {
	AccountID pgtype.UUID
	Provider  string
	Subject   string
}

func (q *Queries) CreateLoginIdentity(ctx context.Context, arg CreateLoginIdentityParams) (LoginIdentity, error) {
	row := q.db.QueryRow(ctx, createLoginIdentity, arg.AccountID, arg.Provider, arg.Subject)
	var i LoginIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.Subject,
		&i.LinkedAt,
	)
	return i, err
}

const getLoginIdentity = `-- name: GetLoginIdentity :one
SELECT id, account_id, provider, subject, linked_at
FROM login_identities
WHERE provider = $1 AND subject = $2
`

type GetLoginIdentityParams struct {
	Provider string
	Subject  string
}

func (q *Queries) GetLoginIdentity(ctx context.Context, arg GetLoginIdentityParams) (LoginIdentity, error) {
	row := q.db.QueryRow(ctx, getLoginIdentity, arg.Provider, arg.Subject)
	var i LoginIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.Subject,
		&i.LinkedAt,
	)
	return i, err
}

const listLoginIdentities = `-- name: ListLoginIdentities :many
SELECT id, account_id, provider, subject, linked_at
FROM login_identities
WHERE account_id = $1
ORDER BY linked_at, provider
`

func (q *Queries) ListLoginIdentities(ctx context.Context, accountID pgtype.UUID) ([]LoginIdentity, error) {
	rows, err := q.db.Query(ctx, listLoginIdentities, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoginIdentity
	for rows.Next() {
		var i LoginIdentity
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Provider,
			&i.Subject,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
