// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (account_id, project_id, content)
VALUES ($1, $3::uuid, $2)
RETURNING id, account_id, project_id, content, created_at, updated_at
`

type CreateNoteParams struct {
	AccountID pgtype.UUID
	Content   string
	ProjectID pgtype.UUID
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.AccountID, arg.Content, arg.ProjectID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ProjectID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes WHERE id = $1 AND account_id = $2
`

type DeleteNoteParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNote = `-- name: GetNote :one
SELECT id, account_id, project_id, content, created_at, updated_at
FROM notes WHERE id = $1 AND account_id = $2
`

type GetNoteParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNote, arg.ID, arg.AccountID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ProjectID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInboxNotes = `-- name: ListInboxNotes :many
SELECT id, account_id, project_id, content, created_at, updated_at
FROM notes
WHERE account_id = $1 AND project_id IS NULL
  AND ($2::timestamptz IS NULL
       OR (created_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type ListInboxNotesParams struct {
	AccountID pgtype.UUID
	CursorAt  pgtype.Timestamptz
	CursorID  pgtype.UUID
	PageSize  int32
}

func (q *Queries) ListInboxNotes(ctx context.Context, arg ListInboxNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listInboxNotes,
		arg.AccountID,
		arg.CursorAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ProjectID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectNotes = `-- name: ListProjectNotes :many
SELECT id, account_id, project_id, content, created_at, updated_at
FROM notes
WHERE account_id = $1 AND project_id = $2
  AND ($3::timestamptz IS NULL
       OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5::int
`

type ListProjectNotesParams struct {
	AccountID pgtype.UUID
	ProjectID pgtype.UUID
	CursorAt  pgtype.Timestamptz
	CursorID  pgtype.UUID
	PageSize  int32
}

func (q *Queries) ListProjectNotes(ctx context.Context, arg ListProjectNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listProjectNotes,
		arg.AccountID,
		arg.ProjectID,
		arg.CursorAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ProjectID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNote = `-- name: LockNote :one
SELECT id, account_id, project_id, content, created_at, updated_at
FROM notes WHERE id = $1 AND account_id = $2 FOR UPDATE
`

type LockNoteParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) LockNote(ctx context.Context, arg LockNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, lockNote, arg.ID, arg.AccountID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ProjectID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockNoteProject = `-- name: LockNoteProject :one
SELECT id, account_id, name, description, created_at, updated_at, archived_at
FROM projects WHERE id = $1 AND account_id = $2 FOR SHARE
`

type LockNoteProjectParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) LockNoteProject(ctx context.Context, arg LockNoteProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, lockNoteProject, arg.ID, arg.AccountID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes SET content = $3, project_id = $4::uuid, updated_at = now()
WHERE id = $1 AND account_id = $2
RETURNING id, account_id, project_id, content, created_at, updated_at
`

type UpdateNoteParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Content   string
	ProjectID pgtype.UUID
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.ID,
		arg.AccountID,
		arg.Content,
		arg.ProjectID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ProjectID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
