// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProject = `-- name: ArchiveProject :execrows
UPDATE projects SET archived_at = now(), updated_at = now()
WHERE id = $1 AND account_id = $2 AND archived_at IS NULL
`

type ArchiveProjectParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveProject, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (account_id, name, description)
VALUES ($1, $2, $3::text)
RETURNING id, account_id, name, description, created_at, updated_at, archived_at
`

type CreateProjectParams struct {
	AccountID   pgtype.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.AccountID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, account_id, name, description, created_at, updated_at, archived_at
FROM projects WHERE id = $1 AND account_id = $2
`

type GetProjectParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.AccountID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listActiveProjects = `-- name: ListActiveProjects :many
SELECT id, account_id, name, description, created_at, updated_at, archived_at
FROM projects WHERE account_id = $1 AND archived_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListActiveProjects(ctx context.Context, accountID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listActiveProjects, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedProjects = `-- name: ListArchivedProjects :many
SELECT id, account_id, name, description, created_at, updated_at, archived_at
FROM projects WHERE account_id = $1 AND archived_at IS NOT NULL
ORDER BY archived_at DESC, id DESC
`

func (q *Queries) ListArchivedProjects(ctx context.Context, accountID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listArchivedProjects, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveProject = `-- name: UnarchiveProject :execrows
UPDATE projects SET archived_at = NULL, updated_at = now()
WHERE id = $1 AND account_id = $2 AND archived_at IS NOT NULL
`

type UnarchiveProjectParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) UnarchiveProject(ctx context.Context, arg UnarchiveProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, unarchiveProject, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    name = CASE WHEN $1::boolean THEN $2::text ELSE projects.name END,
    description = CASE WHEN $3::boolean THEN $4::text ELSE projects.description END,
    updated_at = now()
WHERE id = $5 AND account_id = $6 AND archived_at IS NULL
RETURNING id, account_id, name, description, created_at, updated_at, archived_at
`

type UpdateProjectParams struct {
	NameSet        bool
	Name           string
	DescriptionSet bool
	Description    pgtype.Text
	ID             pgtype.UUID
	AccountID      pgtype.UUID
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.NameSet,
		arg.Name,
		arg.DescriptionSet,
		arg.Description,
		arg.ID,
		arg.AccountID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
