// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateSession = `-- name: AuthenticateSession :one
SELECT s.id AS session_id, s.account_id, s.authenticated_at,
       s.last_used_at, now()::timestamptz AS checked_at,
       a.username, a.time_zone, a.created_at
FROM sessions AS s
JOIN accounts AS a ON s.account_id = a.id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.last_used_at > now() - interval '31 days'
  AND a.deletion_requested_at IS NULL
`

type AuthenticateSessionRow struct {
	SessionID       pgtype.UUID
	AccountID       pgtype.UUID
	AuthenticatedAt pgtype.Timestamptz
	LastUsedAt      pgtype.Timestamptz
	CheckedAt       pgtype.Timestamptz
	Username        string
	TimeZone        string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) AuthenticateSession(ctx context.Context, tokenHash []byte) (AuthenticateSessionRow, error) {
	row := q.db.QueryRow(ctx, authenticateSession, tokenHash)
	var i AuthenticateSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.AccountID,
		&i.AuthenticatedAt,
		&i.LastUsedAt,
		&i.CheckedAt,
		&i.Username,
		&i.TimeZone,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (account_id, token_hash, user_agent, device_label)
SELECT accounts.id, $1, $2, $3
FROM accounts
WHERE accounts.id = $4 AND accounts.deletion_requested_at IS NULL
RETURNING sessions.id, sessions.account_id, sessions.token_hash,
          sessions.user_agent, sessions.device_label, sessions.created_at,
          sessions.last_used_at, sessions.authenticated_at, sessions.revoked_at
`

type CreateSessionParams struct {
	TokenHash   []byte
	UserAgent   string
	DeviceLabel string
	AccountID   pgtype.UUID
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserAgent,
		arg.DeviceLabel,
		arg.AccountID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.UserAgent,
		&i.DeviceLabel,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.AuthenticatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, user_agent, device_label, created_at, last_used_at, authenticated_at
FROM sessions
WHERE account_id = $1
  AND revoked_at IS NULL
  AND last_used_at > now() - interval '31 days'
ORDER BY last_used_at DESC, id
`

type ListActiveSessionsRow struct {
	ID              pgtype.UUID
	UserAgent       string
	DeviceLabel     string
	CreatedAt       pgtype.Timestamptz
	LastUsedAt      pgtype.Timestamptz
	AuthenticatedAt pgtype.Timestamptz
}

func (q *Queries) ListActiveSessions(ctx context.Context, accountID pgtype.UUID) ([]ListActiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSessionsRow
	for rows.Next() {
		var i ListActiveSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserAgent,
			&i.DeviceLabel,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.AuthenticatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessions = `-- name: RevokeAllSessions :execrows
UPDATE sessions
SET revoked_at = now()
WHERE account_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllSessions(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllSessions, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = now()
WHERE id = $1 AND account_id = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :execrows
UPDATE sessions AS s
SET last_used_at = now()
FROM accounts AS a
WHERE s.id = $1
  AND s.account_id = a.id
  AND s.revoked_at IS NULL
  AND s.last_used_at > now() - interval '31 days'
  AND s.last_used_at <= now() - interval '1 day'
  AND a.deletion_requested_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
