// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram_login.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveTelegramAttempt = `-- name: ApproveTelegramAttempt :execrows
UPDATE telegram_login_attempts SET approved_at = now(), telegram_subject = $2
WHERE id = $1 AND callback_claimed_at IS NOT NULL AND approved_at IS NULL AND expires_at > now()
`

type ApproveTelegramAttemptParams struct {
	ID              pgtype.UUID
	TelegramSubject pgtype.Text
}

func (q *Queries) ApproveTelegramAttempt(ctx context.Context, arg ApproveTelegramAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveTelegramAttempt, arg.ID, arg.TelegramSubject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimTelegramCallback = `-- name: ClaimTelegramCallback :one
UPDATE telegram_login_attempts SET callback_claimed_at = now()
WHERE state_hash = $1 AND purpose = 'sign_in' AND expires_at > now()
  AND callback_claimed_at IS NULL AND approved_at IS NULL
RETURNING id, pkce_verifier_ciphertext, nonce
`

type ClaimTelegramCallbackRow struct {
	ID                     pgtype.UUID
	PkceVerifierCiphertext []byte
	Nonce                  string
}

func (q *Queries) ClaimTelegramCallback(ctx context.Context, stateHash []byte) (ClaimTelegramCallbackRow, error) {
	row := q.db.QueryRow(ctx, claimTelegramCallback, stateHash)
	var i ClaimTelegramCallbackRow
	err := row.Scan(&i.ID, &i.PkceVerifierCiphertext, &i.Nonce)
	return i, err
}

const completeTelegramAttempt = `-- name: CompleteTelegramAttempt :execrows
UPDATE telegram_login_attempts SET completed_at = now(), recovery_ticket_hash = $2
WHERE id = $1 AND approved_at IS NOT NULL AND completed_at IS NULL AND expires_at > now()
`

type CompleteTelegramAttemptParams struct {
	ID                 pgtype.UUID
	RecoveryTicketHash []byte
}

func (q *Queries) CompleteTelegramAttempt(ctx context.Context, arg CompleteTelegramAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeTelegramAttempt, arg.ID, arg.RecoveryTicketHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeTelegramRecovery = `-- name: ConsumeTelegramRecovery :execrows
UPDATE telegram_login_attempts SET recovery_ticket_hash = $2
WHERE recovery_ticket_hash = $1 AND completed_at > now() - interval '10 minutes'
`

type ConsumeTelegramRecoveryParams struct {
	RecoveryTicketHash   []byte
	RecoveryTicketHash_2 []byte
}

func (q *Queries) ConsumeTelegramRecovery(ctx context.Context, arg ConsumeTelegramRecoveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeTelegramRecovery, arg.RecoveryTicketHash, arg.RecoveryTicketHash_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTelegramAttempt = `-- name: CreateTelegramAttempt :one
INSERT INTO telegram_login_attempts (state_hash, pkce_verifier_ciphertext, nonce, poll_secret_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4, 'sign_in', now() + interval '10 minutes')
RETURNING id
`

type CreateTelegramAttemptParams struct {
	StateHash              []byte
	PkceVerifierCiphertext []byte
	Nonce                  string
	PollSecretHash         []byte
}

func (q *Queries) CreateTelegramAttempt(ctx context.Context, arg CreateTelegramAttemptParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTelegramAttempt,
		arg.StateHash,
		arg.PkceVerifierCiphertext,
		arg.Nonce,
		arg.PollSecretHash,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockTelegramAttempt = `-- name: LockTelegramAttempt :one
SELECT id, telegram_subject, approved_at, completed_at, expires_at
FROM telegram_login_attempts
WHERE id = $1 AND poll_secret_hash = $2 AND purpose = 'sign_in' FOR UPDATE
`

type LockTelegramAttemptParams struct {
	ID             pgtype.UUID
	PollSecretHash []byte
}

type LockTelegramAttemptRow struct {
	ID              pgtype.UUID
	TelegramSubject pgtype.Text
	ApprovedAt      pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) LockTelegramAttempt(ctx context.Context, arg LockTelegramAttemptParams) (LockTelegramAttemptRow, error) {
	row := q.db.QueryRow(ctx, lockTelegramAttempt, arg.ID, arg.PollSecretHash)
	var i LockTelegramAttemptRow
	err := row.Scan(
		&i.ID,
		&i.TelegramSubject,
		&i.ApprovedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const lockTelegramRecovery = `-- name: LockTelegramRecovery :one
SELECT id, telegram_subject FROM telegram_login_attempts
WHERE recovery_ticket_hash = $1 AND completed_at > now() - interval '10 minutes' FOR UPDATE
`

type LockTelegramRecoveryRow struct {
	ID              pgtype.UUID
	TelegramSubject pgtype.Text
}

func (q *Queries) LockTelegramRecovery(ctx context.Context, recoveryTicketHash []byte) (LockTelegramRecoveryRow, error) {
	row := q.db.QueryRow(ctx, lockTelegramRecovery, recoveryTicketHash)
	var i LockTelegramRecoveryRow
	err := row.Scan(&i.ID, &i.TelegramSubject)
	return i, err
}

const pruneTelegramAttempts = `-- name: PruneTelegramAttempts :exec
DELETE FROM telegram_login_attempts WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) PruneTelegramAttempts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneTelegramAttempts)
	return err
}

const restoreTelegramAccount = `-- name: RestoreTelegramAccount :one
UPDATE accounts AS a SET deletion_requested_at = NULL
FROM login_identities AS i
WHERE i.subject = $1 AND i.provider = 'telegram' AND i.account_id = a.id
  AND a.deletion_requested_at IS NOT NULL
  AND a.deletion_requested_at > now() - interval '30 days'
RETURNING a.id
`

func (q *Queries) RestoreTelegramAccount(ctx context.Context, subject string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, restoreTelegramAccount, subject)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
